version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /hello_input_wdl_example.wdl
    testParameterFiles:
      - /input.json
  - subclass: NFL      
    primaryDescriptorPath: /nextflow.config
    name: nextflow_example 
  - subclass: GALAXY
    primaryDescriptorPath: /Galaxy-Workflow-reverse_file_galaxy_workflow.ga
    name: galaxy_example
tools:
  - subclass: CWL
    primaryDescriptorPath: /cat3-tool-mediumcut.cwl
    testParameterFiles:
      - /cat-job.json
    name: cwl_example
