version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /hello_input_wdl_example.wdl
    testParameterFiles:
      - /input.json
  - subclass: NFL      
    primaryDescriptorPath: /nextflow.config
    name: nextflow_example 
